apiVersion: apps/v1
kind: Deployment
metadata:
  name: qsapi-deployment
  labels:
    app: qsapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qsapi
  template:
    metadata:
      labels:
        app: qsapi
    spec:
      containers:
      - name: qsapi
        image: mvdijk01/quantifiedstudent:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: qsapi-service
spec:
  selector:
    app: qsapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer